### PR TITLE
Bump version: 2.2.0 → 2.3.0

### PR DESCRIPTION
**Pull request by apaparazzi0329**

### CODE REVIEW

**Review by kevinkowa — APPROVED** [review]
LGTM!

**Comment by lwblackledge** [comment]
Thanks!

**Comment by lwblackledge** [comment]
I don't think the build for this finished yet - I don't see the assets on the release tag nor the new version in [MvnRepository](https://mvnrepository.com/artifact/com.ibm.watson.developer_cloud/watson-spring-boot-starter). Looks like the tag is behind the merge of the SDK update?
https://github.com/watson-developer-cloud/spring-boot-starter/compare/v2.3.0...master

**Comment by kevinkowa** [comment]
hmm odd, I see. For some reason it got uploaded to sonatype even if this was the case. I'll take a look at it, seems like we need to update our credentials

**Pull request merged**
